import type { Department, OfficeTask } from "./types";

export const DEPARTMENTS: Department[] = [
  {
    id: "sales",
    name: "ฝ่ายขาย",
    shortName: "ขาย",
    color: "#34d399",
    roomX: 4,
    roomY: 8,
    roomW: 28,
    roomH: 36,
    icon: "💼",
    employees: [
      { id: "e-s1", name: "มายด์", role: "Sales Lead", avatarHue: 155, robotId: "silver-knight", deskX: 12, deskY: 18 },
      { id: "e-s2", name: "ต้น", role: "AE", avatarHue: 190, robotId: "blue-mechanic", deskX: 22, deskY: 28 },
    ],
    steps: [
      { id: "s1", order: 1, title: "รับลีด", description: "คัดกรองลีดจากช่องทางต่าง ๆ", ownerRole: "AE", typicalHours: 2 },
      { id: "s2", order: 2, title: "ติดต่อลูกค้า", description: "นัดหมายและทำความเข้าใจความต้องการ", ownerRole: "AE", typicalHours: 4 },
      { id: "s3", order: 3, title: "เสนอราคา", description: "จัดทำใบเสนอราคาและแพ็กเกจ", ownerRole: "Sales Lead", typicalHours: 3 },
      { id: "s4", order: 4, title: "รออนุมัติดีล", description: "หัวหน้า/ผู้บริหารอนุมัติส่วนลด", ownerRole: "Sales Lead", typicalHours: 8 },
      { id: "s5", order: 5, title: "ปิดการขาย", description: "เซ็นสัญญาและส่งต่อบัญชี/คลัง", ownerRole: "AE", typicalHours: 2 },
    ],
  },
  {
    id: "marketing",
    name: "การตลาด",
    shortName: "การตลาด",
    color: "#fb7185",
    roomX: 36,
    roomY: 8,
    roomW: 30,
    roomH: 36,
    icon: "📣",
    employees: [
      { id: "e-m1", name: "พลอย", role: "Content Lead", avatarHue: 330, robotId: "lavender-v", deskX: 44, deskY: 16 },
      { id: "e-m2", name: "กัน", role: "Media Buyer", avatarHue: 25, robotId: "orange-crab", deskX: 56, deskY: 30 },
    ],
    steps: [
      { id: "m1", order: 1, title: "บรีฟแคมเปญ", description: "รับโจทย์และกำหนด KPI", ownerRole: "Content Lead", typicalHours: 3 },
      { id: "m2", order: 2, title: "ผลิตคอนเทนต์", description: "เขียนแคปชัน/สคริปต์/ภาพ", ownerRole: "Content Lead", typicalHours: 10 },
      { id: "m3", order: 3, title: "ตรวจคุณภาพ", description: "ตรวจโทนเสียงและ disclosure", ownerRole: "Content Lead", typicalHours: 2 },
      { id: "m4", order: 4, title: "ขออนุมัติโพสต์", description: "รอ Approve ก่อนเผยแพร่", ownerRole: "Media Buyer", typicalHours: 6 },
      { id: "m5", order: 5, title: "ปล่อยและวัดผล", description: "โพสต์และสรุปเมตริก", ownerRole: "Media Buyer", typicalHours: 4 },
    ],
  },
  {
    id: "accounting",
    name: "บัญชี",
    shortName: "บัญชี",
    color: "#60a5fa",
    roomX: 70,
    roomY: 8,
    roomW: 26,
    roomH: 36,
    icon: "📒",
    employees: [
      { id: "e-a1", name: "นุ่น", role: "Accountant", avatarHue: 210, robotId: "purple-astro", deskX: 78, deskY: 18 },
      { id: "e-a2", name: "โอ๊ต", role: "AP/AR", avatarHue: 245, robotId: "maroon-leader", deskX: 88, deskY: 30 },
    ],
    steps: [
      { id: "a1", order: 1, title: "รับเอกสาร", description: "รวบรวมใบแจ้งหนี้/ใบเสร็จ", ownerRole: "AP/AR", typicalHours: 2 },
      { id: "a2", order: 2, title: "ตรวจสอบ", description: "จับคู่ PO และยอดเงิน", ownerRole: "Accountant", typicalHours: 4 },
      { id: "a3", order: 3, title: "บันทึกบัญชี", description: "ลงระบบและแนบหลักฐาน", ownerRole: "Accountant", typicalHours: 3 },
      { id: "a4", order: 4, title: "รออนุมัติจ่าย", description: "ผู้มีอำนาจลงนามอนุมัติ", ownerRole: "Accountant", typicalHours: 12 },
      { id: "a5", order: 5, title: "ปิดรายการ", description: "จ่ายเงินและเก็บไฟล์", ownerRole: "AP/AR", typicalHours: 2 },
    ],
  },
  {
    id: "warehouse",
    name: "คลังสินค้า",
    shortName: "คลัง",
    color: "#fbbf24",
    roomX: 4,
    roomY: 50,
    roomW: 28,
    roomH: 42,
    icon: "📦",
    employees: [
      { id: "e-w1", name: "โจ", role: "Warehouse Lead", avatarHue: 45, robotId: "yellow-worker", deskX: 12, deskY: 62 },
      { id: "e-w2", name: "เบียร์", role: "Picker", avatarHue: 85, robotId: "green-tank", deskX: 22, deskY: 78 },
    ],
    steps: [
      { id: "w1", order: 1, title: "รับออเดอร์", description: "ดึงใบเบิกจากระบบ", ownerRole: "Warehouse Lead", typicalHours: 1 },
      { id: "w2", order: 2, title: "จัดของ", description: "หยิบสินค้าตามรายการ", ownerRole: "Picker", typicalHours: 3 },
      { id: "w3", order: 3, title: "แพ็กสินค้า", description: "ตรวจคุณภาพและแพ็ก", ownerRole: "Picker", typicalHours: 2 },
      { id: "w4", order: 4, title: "ตรวจก่อนส่ง", description: "เช็กจำนวนและที่อยู่", ownerRole: "Warehouse Lead", typicalHours: 1 },
      { id: "w5", order: 5, title: "ส่งมอบ", description: "ส่งขนส่งและอัปเดตสถานะ", ownerRole: "Warehouse Lead", typicalHours: 2 },
    ],
  },
  {
    id: "procurement",
    name: "จัดซื้อ",
    shortName: "จัดซื้อ",
    color: "#c084fc",
    roomX: 36,
    roomY: 50,
    roomW: 30,
    roomH: 42,
    icon: "🛒",
    employees: [
      { id: "e-p1", name: "ฟ้า", role: "Buyer", avatarHue: 280, robotId: "red-tripod", deskX: 44, deskY: 60 },
      { id: "e-p2", name: "ติ๊ก", role: "Vendor Coord", avatarHue: 305, robotId: "blue-mechanic", deskX: 56, deskY: 76 },
    ],
    steps: [
      { id: "p1", order: 1, title: "รับคำขอซื้อ", description: "ตรวจ PR จากแผนกอื่น", ownerRole: "Buyer", typicalHours: 2 },
      { id: "p2", order: 2, title: "เปรียบเทียบราคา", description: "ขอใบเสนอจากผู้ขาย 2–3 ราย", ownerRole: "Buyer", typicalHours: 8 },
      { id: "p3", order: 3, title: "สร้าง PO", description: "ออกใบสั่งซื้อ", ownerRole: "Vendor Coord", typicalHours: 2 },
      { id: "p4", order: 4, title: "รออนุมัติ PO", description: "ผู้บริหารอนุมัติงบ", ownerRole: "Buyer", typicalHours: 10 },
      { id: "p5", order: 5, title: "ติดตามของเข้า", description: "ประสานคลังรับของ", ownerRole: "Vendor Coord", typicalHours: 6 },
    ],
  },
  {
    id: "support",
    name: "บริการลูกค้า",
    shortName: "บริการ",
    color: "#2dd4bf",
    roomX: 70,
    roomY: 50,
    roomW: 26,
    roomH: 22,
    icon: "🎧",
    employees: [
      { id: "e-c1", name: "มิ้นต์", role: "CS Agent", avatarHue: 170, robotId: "lavender-v", deskX: 78, deskY: 58 },
      { id: "e-c2", name: "แอน", role: "CS Lead", avatarHue: 140, robotId: "orange-crab", deskX: 88, deskY: 66 },
    ],
    steps: [
      { id: "c1", order: 1, title: "รับเคส", description: "เปิดตั๋วจากแชท/อีเมล", ownerRole: "CS Agent", typicalHours: 0.5 },
      { id: "c2", order: 2, title: "วิเคราะห์ปัญหา", description: "ตรวจออเดอร์และประวัติ", ownerRole: "CS Agent", typicalHours: 2 },
      { id: "c3", order: 3, title: "แก้ปัญหา", description: "คืนเงิน/เปลี่ยนสินค้า/แนะนำ", ownerRole: "CS Agent", typicalHours: 4 },
      { id: "c4", order: 4, title: "รออนุมัติพิเศษ", description: "เคสส่วนลดพิเศษรอหัวหน้า", ownerRole: "CS Lead", typicalHours: 6 },
      { id: "c5", order: 5, title: "ปิดเคส", description: "ยืนยันกับลูกค้าและสรุป", ownerRole: "CS Lead", typicalHours: 1 },
    ],
  },
  {
    id: "exec",
    name: "ผู้บริหาร",
    shortName: "ผู้บริหาร",
    color: "#67e8f9",
    roomX: 70,
    roomY: 74,
    roomW: 26,
    roomH: 18,
    icon: "🏢",
    employees: [
      { id: "e-x1", name: "คุณเอ", role: "CEO", avatarHue: 195, robotId: "maroon-leader", deskX: 78, deskY: 82 },
      { id: "e-x2", name: "คุณบี", role: "COO", avatarHue: 320, robotId: "silver-knight", deskX: 88, deskY: 86 },
    ],
    steps: [
      { id: "x1", order: 1, title: "รับคำขออนุมัติ", description: "รวมคำขอจากทุกแผนก", ownerRole: "COO", typicalHours: 1 },
      { id: "x2", order: 2, title: "ทบทวนข้อมูล", description: "ดูงบ ผลกระทบ และความเสี่ยง", ownerRole: "COO", typicalHours: 3 },
      { id: "x3", order: 3, title: "ประชุมตัดสินใจ", description: "หารือสั้น ๆ หากยอดสูง", ownerRole: "CEO", typicalHours: 2 },
      { id: "x4", order: 4, title: "อนุมัติ/ตีกลับ", description: "ลงนามหรือขอแก้ไข", ownerRole: "CEO", typicalHours: 1 },
      { id: "x5", order: 5, title: "ติดตามผล", description: "ตรวจว่าแผนกดำเนินการต่อแล้ว", ownerRole: "COO", typicalHours: 4 },
    ],
  },
];

export const TASKS: OfficeTask[] = [
  // Sales
  {
    id: "t-s1",
    title: "ดีลร้านกาแฟสายสีเขียว",
    description: "ลูกค้าสนใจแพ็กเกจ affiliate รายเดือน ขอส่วนลด 8%",
    departmentId: "sales",
    stepId: "s4",
    status: "waiting_approval",
    assigneeId: "e-s1",
    priority: "high",
    createdAt: "2026-07-25T08:00:00Z",
    updatedAt: "2026-07-25T11:30:00Z",
    dueLabel: "วันนี้ 17:00",
    tags: ["B2B", "ส่วนลด"],
    elapsedHours: 6,
    checklist: [
      { label: "ส่งใบเสนอราคา", done: true },
      { label: "แนบประวัติลูกค้า", done: true },
      { label: "รอหัวหน้าอนุมัติส่วนลด", done: false },
    ],
  },
  {
    id: "t-s2",
    title: "ติดต่อลีดจาก TikTok Live",
    description: "ลีด 12 รายจากไลฟ์คืนวาน ต้องคอลภายในวันนี้",
    departmentId: "sales",
    stepId: "s2",
    status: "in_progress",
    assigneeId: "e-s2",
    priority: "medium",
    createdAt: "2026-07-25T07:30:00Z",
    updatedAt: "2026-07-25T10:00:00Z",
    dueLabel: "วันนี้ 15:00",
    tags: ["ลีด", "TikTok"],
    elapsedHours: 3,
    checklist: [
      { label: "คัดลีดคุณภาพ", done: true },
      { label: "โทรรอบแรก", done: false },
      { label: "นัดเดโม", done: false },
    ],
  },
  {
    id: "t-s3",
    title: "ปิดดีลครีเอเตอร์ความงาม",
    description: "เซ็นสัญญาและส่งต่อบัญชีออกใบแจ้งหนี้",
    departmentId: "sales",
    stepId: "s5",
    status: "done",
    assigneeId: "e-s2",
    priority: "medium",
    createdAt: "2026-07-24T09:00:00Z",
    updatedAt: "2026-07-25T09:15:00Z",
    dueLabel: "เสร็จแล้ว",
    tags: ["ปิดดีล"],
    elapsedHours: 5,
    checklist: [
      { label: "เซ็นสัญญา", done: true },
      { label: "ส่งบัญชี", done: true },
    ],
  },
  {
    id: "t-s4",
    title: "ลีดงานอีเวนต์ปลายเดือน",
    description: "ยังไม่เริ่มคัดกรอง — คิวถัดไป",
    departmentId: "sales",
    stepId: "s1",
    status: "backlog",
    assigneeId: "e-s1",
    priority: "low",
    createdAt: "2026-07-25T06:00:00Z",
    updatedAt: "2026-07-25T06:00:00Z",
    dueLabel: "พรุ่งนี้",
    tags: ["ลีด"],
    elapsedHours: 0,
    checklist: [{ label: "คัดลีดจากฟอร์ม", done: false }],
  },
  // Marketing
  {
    id: "t-m1",
    title: "แคมเปญรีลพัดลมมือถือ",
    description: "สคริปต์ 25 วิ + caption Facebook พร้อม disclosure",
    departmentId: "marketing",
    stepId: "m4",
    status: "waiting_approval",
    assigneeId: "e-m1",
    priority: "high",
    createdAt: "2026-07-25T07:00:00Z",
    updatedAt: "2026-07-25T12:00:00Z",
    dueLabel: "วันนี้ 18:00",
    tags: ["Reels", "Affiliate"],
    elapsedHours: 8,
    checklist: [
      { label: "เขียนสคริปต์", done: true },
      { label: "ใส่ disclosure", done: true },
      { label: "รอ Approve", done: false },
    ],
  },
  {
    id: "t-m2",
    title: "ชุดคอนเทนต์ครีมกันแดด",
    description: "ทำ 3 มุมขาย ไม่ขายแข็ง โทนช่วยเลือกของ",
    departmentId: "marketing",
    stepId: "m2",
    status: "in_progress",
    assigneeId: "e-m1",
    priority: "medium",
    createdAt: "2026-07-25T08:30:00Z",
    updatedAt: "2026-07-25T13:00:00Z",
    dueLabel: "วันนี้ 20:00",
    tags: ["คอนเทนต์"],
    elapsedHours: 4,
    checklist: [
      { label: "Hook 5 แบบ", done: true },
      { label: "Caption FB", done: false },
      { label: "Hashtag", done: false },
    ],
  },
  {
    id: "t-m3",
    title: "สรุปเมตริกโพสต์เมื่อวาน",
    description: "views/clicks/orders สำหรับ evening report",
    departmentId: "marketing",
    stepId: "m5",
    status: "done",
    assigneeId: "e-m2",
    priority: "medium",
    createdAt: "2026-07-24T18:00:00Z",
    updatedAt: "2026-07-25T08:40:00Z",
    dueLabel: "เสร็จแล้ว",
    tags: ["รายงาน"],
    elapsedHours: 2,
    checklist: [
      { label: "ดึงตัวเลข", done: true },
      { label: "ส่งแดชบอร์ด", done: true },
    ],
  },
  {
    id: "t-m4",
    title: "บรีฟแคมเปญวันแม่",
    description: "รอโจทย์จากฝ่ายขายก่อนเริ่ม",
    departmentId: "marketing",
    stepId: "m1",
    status: "backlog",
    assigneeId: "e-m2",
    priority: "low",
    createdAt: "2026-07-25T05:00:00Z",
    updatedAt: "2026-07-25T05:00:00Z",
    dueLabel: "สัปดาห์หน้า",
    tags: ["ซีซัน"],
    elapsedHours: 0,
    checklist: [{ label: "นัดบรีฟ", done: false }],
  },
  // Accounting
  {
    id: "t-a1",
    title: "จ่ายค่าคอมครีเอเตอร์รอบ 2",
    description: "ยอด ฿42,500 รออนุมัติจ่าย",
    departmentId: "accounting",
    stepId: "a4",
    status: "waiting_approval",
    assigneeId: "e-a1",
    priority: "high",
    createdAt: "2026-07-24T10:00:00Z",
    updatedAt: "2026-07-25T09:00:00Z",
    dueLabel: "วันนี้ 16:00",
    tags: ["จ่ายเงิน"],
    elapsedHours: 14,
    checklist: [
      { label: "ตรวจใบแจ้งหนี้", done: true },
      { label: "จับคู่ PO", done: true },
      { label: "รอลงนาม", done: false },
    ],
  },
  {
    id: "t-a2",
    title: "บันทึกรายรับ Shopee",
    description: "กระทบยอดออเดอร์สัปดาห์นี้",
    departmentId: "accounting",
    stepId: "a3",
    status: "in_progress",
    assigneeId: "e-a2",
    priority: "medium",
    createdAt: "2026-07-25T08:00:00Z",
    updatedAt: "2026-07-25T11:00:00Z",
    dueLabel: "วันนี้",
    tags: ["รายรับ"],
    elapsedHours: 3,
    checklist: [
      { label: "ดึงรายงาน", done: true },
      { label: "ลงระบบ", done: false },
    ],
  },
  {
    id: "t-a3",
    title: "ปิดบิลค่าโฆษณา Meta",
    description: "จ่ายและเก็บสลิปเรียบร้อย",
    departmentId: "accounting",
    stepId: "a5",
    status: "done",
    assigneeId: "e-a2",
    priority: "low",
    createdAt: "2026-07-23T09:00:00Z",
    updatedAt: "2026-07-24T16:00:00Z",
    dueLabel: "เสร็จแล้ว",
    tags: ["โฆษณา"],
    elapsedHours: 7,
    checklist: [
      { label: "จ่ายเงิน", done: true },
      { label: "เก็บไฟล์", done: true },
    ],
  },
  // Warehouse
  {
    id: "t-w1",
    title: "แพ็กออเดอร์รีวิวสินค้าตัวอย่าง",
    description: "ส่งของตัวอย่างให้ครีเอเตอร์ 5 คน",
    departmentId: "warehouse",
    stepId: "w3",
    status: "in_progress",
    assigneeId: "e-w2",
    priority: "high",
    createdAt: "2026-07-25T07:00:00Z",
    updatedAt: "2026-07-25T12:30:00Z",
    dueLabel: "วันนี้ 14:00",
    tags: ["ตัวอย่าง", "ครีเอเตอร์"],
    elapsedHours: 5,
    checklist: [
      { label: "หยิบสินค้า", done: true },
      { label: "แพ็ก", done: false },
      { label: "พิมพ์ที่อยู่", done: false },
    ],
  },
  {
    id: "t-w2",
    title: "ส่งพัสดุรอบบ่าย",
    description: "รอตรวจก่อนส่ง 8 กล่อง",
    departmentId: "warehouse",
    stepId: "w4",
    status: "waiting_approval",
    assigneeId: "e-w1",
    priority: "medium",
    createdAt: "2026-07-25T09:00:00Z",
    updatedAt: "2026-07-25T13:00:00Z",
    dueLabel: "วันนี้ 15:30",
    tags: ["ขนส่ง"],
    elapsedHours: 4,
    checklist: [
      { label: "เช็กจำนวน", done: true },
      { label: "หัวหน้าเซ็นออก", done: false },
    ],
  },
  {
    id: "t-w3",
    title: "รับสินค้าเข้าจากจัดซื้อ",
    description: "รอ PO อนุมัติก่อนจัดวางชั้น",
    departmentId: "warehouse",
    stepId: "w1",
    status: "backlog",
    assigneeId: "e-w1",
    priority: "low",
    createdAt: "2026-07-25T06:30:00Z",
    updatedAt: "2026-07-25T06:30:00Z",
    dueLabel: "รอสัญญาณ",
    tags: ["รับเข้า"],
    elapsedHours: 0,
    checklist: [{ label: "เตรียมพื้นที่ชั้น B", done: false }],
  },
  // Procurement
  {
    id: "t-p1",
    title: "PO กล่องแพ็กเกจรอบใหม่",
    description: "งบ ฿28,000 รอผู้บริหารอนุมัติ",
    departmentId: "procurement",
    stepId: "p4",
    status: "waiting_approval",
    assigneeId: "e-p1",
    priority: "high",
    createdAt: "2026-07-24T14:00:00Z",
    updatedAt: "2026-07-25T10:00:00Z",
    dueLabel: "วันนี้",
    tags: ["PO", "แพ็กเกจ"],
    elapsedHours: 16,
    checklist: [
      { label: "เปรียบเทียบผู้ขาย", done: true },
      { label: "ออก PO", done: true },
      { label: "รออนุมัติ", done: false },
    ],
  },
  {
    id: "t-p2",
    title: "หาซัพพลายสายชาร์จสำรอง",
    description: "ขอใบเสนอ 3 ราย",
    departmentId: "procurement",
    stepId: "p2",
    status: "in_progress",
    assigneeId: "e-p1",
    priority: "medium",
    createdAt: "2026-07-25T08:00:00Z",
    updatedAt: "2026-07-25T11:45:00Z",
    dueLabel: "พรุ่งนี้",
    tags: ["ซัพพลาย"],
    elapsedHours: 4,
    checklist: [
      { label: "ติดต่อผู้ขาย A", done: true },
      { label: "ติดต่อผู้ขาย B", done: false },
      { label: "ติดต่อผู้ขาย C", done: false },
    ],
  },
  {
    id: "t-p3",
    title: "คำขอซื้อขาตั้งมือถือ",
    description: "PR จากฝ่ายการตลาด ยังไม่เริ่ม",
    departmentId: "procurement",
    stepId: "p1",
    status: "backlog",
    assigneeId: "e-p2",
    priority: "low",
    createdAt: "2026-07-25T07:10:00Z",
    updatedAt: "2026-07-25T07:10:00Z",
    dueLabel: "สัปดาห์นี้",
    tags: ["PR"],
    elapsedHours: 0,
    checklist: [{ label: "ตรวจสเปก", done: false }],
  },
  // Support
  {
    id: "t-c1",
    title: "เคสคืนเงินออเดอร์ #8821",
    description: "ลูกค้าได้รับของเสีย ขอคืนเต็มจำนวน",
    departmentId: "support",
    stepId: "c4",
    status: "waiting_approval",
    assigneeId: "e-c2",
    priority: "high",
    createdAt: "2026-07-25T09:20:00Z",
    updatedAt: "2026-07-25T12:10:00Z",
    dueLabel: "ภายใน 4 ชม.",
    tags: ["คืนเงิน"],
    elapsedHours: 3,
    checklist: [
      { label: "ตรวจหลักฐาน", done: true },
      { label: "เสนอคืนเต็ม", done: true },
      { label: "รอหัวหน้าอนุมัติ", done: false },
    ],
  },
  {
    id: "t-c2",
    title: "สอบถามสถานะพัสดุ",
    description: "ลูกค้า 3 เคสถามเลขพัสดุซ้ำ",
    departmentId: "support",
    stepId: "c3",
    status: "in_progress",
    assigneeId: "e-c1",
    priority: "medium",
    createdAt: "2026-07-25T10:00:00Z",
    updatedAt: "2026-07-25T13:20:00Z",
    dueLabel: "วันนี้",
    tags: ["ขนส่ง"],
    elapsedHours: 2,
    checklist: [
      { label: "ตอบเคสที่ 1", done: true },
      { label: "ตอบเคสที่ 2", done: false },
      { label: "ตอบเคสที่ 3", done: false },
    ],
  },
  {
    id: "t-c3",
    title: "ปิดเคสเปลี่ยนสินค้า",
    description: "ลูกค้ายืนยันรับของทดแทนแล้ว",
    departmentId: "support",
    stepId: "c5",
    status: "done",
    assigneeId: "e-c1",
    priority: "low",
    createdAt: "2026-07-24T11:00:00Z",
    updatedAt: "2026-07-25T08:00:00Z",
    dueLabel: "เสร็จแล้ว",
    tags: ["ปิดเคส"],
    elapsedHours: 6,
    checklist: [
      { label: "ส่งของทดแทน", done: true },
      { label: "ยืนยันลูกค้า", done: true },
    ],
  },
  // Exec
  {
    id: "t-x1",
    title: "อนุมัติงบแคมเปญ Q3",
    description: "คำขอจากตลาด ฿120,000",
    departmentId: "exec",
    stepId: "x3",
    status: "in_progress",
    assigneeId: "e-x1",
    priority: "high",
    createdAt: "2026-07-25T08:00:00Z",
    updatedAt: "2026-07-25T13:00:00Z",
    dueLabel: "วันนี้ 17:30",
    tags: ["งบ", "Q3"],
    elapsedHours: 5,
    checklist: [
      { label: "อ่านสรุป COO", done: true },
      { label: "ประชุมสั้น", done: false },
      { label: "ลงนาม", done: false },
    ],
  },
  {
    id: "t-x2",
    title: "อนุมัติ PO กล่องแพ็กเกจ",
    description: "โยงกับจัดซื้อ — ยอด ฿28,000",
    departmentId: "exec",
    stepId: "x4",
    status: "waiting_approval",
    assigneeId: "e-x2",
    priority: "high",
    createdAt: "2026-07-25T10:00:00Z",
    updatedAt: "2026-07-25T12:00:00Z",
    dueLabel: "ด่วน",
    tags: ["PO"],
    elapsedHours: 2,
    checklist: [
      { label: "ตรวจงบคงเหลือ", done: true },
      { label: "อนุมัติ/ตีกลับ", done: false },
    ],
  },
  {
    id: "t-x3",
    title: "รีวิวนโยบาย affiliate disclosure",
    description: "คิวทบทวนเอกสาร mid-year",
    departmentId: "exec",
    stepId: "x1",
    status: "backlog",
    assigneeId: "e-x2",
    priority: "low",
    createdAt: "2026-07-22T09:00:00Z",
    updatedAt: "2026-07-22T09:00:00Z",
    dueLabel: "สัปดาห์หน้า",
    tags: ["นโยบาย"],
    elapsedHours: 0,
    checklist: [{ label: "นัดทบทวน", done: false }],
  },
];

export const STATUS_LABELS: Record<
  import("./types").TaskStatus,
  { label: string; tone: string }
> = {
  in_progress: { label: "กำลังทำ", tone: "bg-[#dceee4] text-[#2a4d3f]" },
  waiting_approval: { label: "รออนุมัติ", tone: "bg-[#f3e0d4] text-[#8a4b2f]" },
  done: { label: "เสร็จแล้ว", tone: "bg-[#e4eaf5] text-[#2f4a72]" },
  backlog: { label: "งานค้าง", tone: "bg-[#eee8dc] text-[#6a5530]" },
};

export function getDepartment(id: string) {
  return DEPARTMENTS.find((d) => d.id === id) ?? DEPARTMENTS[0];
}

export function getEmployee(departmentId: string, employeeId: string) {
  const dept = getDepartment(departmentId);
  return dept.employees.find((e) => e.id === employeeId);
}

export function summarizeTasks(tasks: OfficeTask[]) {
  const today = tasks.filter((t) => t.status !== "backlog");
  const backlog = tasks.filter((t) => t.status === "backlog").length;
  const waiting = tasks.filter((t) => t.status === "waiting_approval").length;
  const active = tasks.filter((t) => t.status === "in_progress" || t.status === "waiting_approval");
  const avg =
    active.length === 0
      ? 0
      : active.reduce((s, t) => s + t.elapsedHours, 0) / active.length;
  return {
    todayCount: today.length,
    backlog,
    waiting,
    avgHours: Math.round(avg * 10) / 10,
  };
}
